"""create form_filing_addresses table

Revision ID: 95a8b0b0ffcb
Revises: 3857ed402cdc
Create Date: 2026-07-02 16:26:00.386268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95a8b0b0ffcb'
down_revision: Union[str, None] = '3857ed402cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_filing_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_number', sa.String(), nullable=False),
    sa.Column('form_title', sa.String(), nullable=False),
    sa.Column('form_url', sa.String(), nullable=True),
    sa.Column('filing_scenario', sa.String(), nullable=False),
    sa.Column('applies_to', sa.String(), nullable=False),
    sa.Column('lockbox_name', sa.String(), nullable=False),
    sa.Column('usps_address', sa.String(), nullable=True),
    sa.Column('courier_address', sa.String(), nullable=True),
    sa.Column('address_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_number', 'filing_scenario', 'lockbox_name', name='uq_form_filing_addresses_form_scenario_lockbox')
    )
    op.create_index(op.f('ix_form_filing_addresses_form_number'), 'form_filing_addresses', ['form_number'], unique=False)
    # NOTE: autogenerate also detected 'removed' checkpoint_blobs/checkpoint_writes/
    # checkpoint_migrations/checkpoints tables here — those are managed by
    # AsyncPostgresSaver.setup() at app startup (see docs/setup.md), not by our
    # SQLAlchemy models, so autogenerate sees them as unmanaged/extraneous.
    # Intentionally stripped out so this migration doesn't drop them.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_filing_addresses_form_number'), table_name='form_filing_addresses')
    op.drop_table('form_filing_addresses')
    # ### end Alembic commands ###
