"""create form_fields table

Revision ID: e7b2d4a91c35
Revises: c3f8a2b6e910
Create Date: 2026-07-08 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7b2d4a91c35'
down_revision: Union[str, None] = 'c3f8a2b6e910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingestion_file_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['ingestion_file_id'], ['ingestion_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_fields_case_id'), 'form_fields', ['case_id'], unique=False)
    op.create_index(op.f('ix_form_fields_ingestion_file_id'), 'form_fields', ['ingestion_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_fields_ingestion_file_id'), table_name='form_fields')
    op.drop_index(op.f('ix_form_fields_case_id'), table_name='form_fields')
    op.drop_table('form_fields')
    # ### end Alembic commands ###
